/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelievingIndexRouteImport } from './routes/relieving/index'
import { Route as OffersIndexRouteImport } from './routes/offers/index'
import { Route as ExperienceIndexRouteImport } from './routes/experience/index'
import { Route as ConfirmationsIndexRouteImport } from './routes/confirmations/index'
import { Route as SlipsNewRouteImport } from './routes/slips/new'
import { Route as SlipsIdRouteImport } from './routes/slips/$id'
import { Route as RelievingNewRouteImport } from './routes/relieving/new'
import { Route as RelievingIdRouteImport } from './routes/relieving/$id'
import { Route as OffersNewRouteImport } from './routes/offers/new'
import { Route as OffersIdRouteImport } from './routes/offers/$id'
import { Route as ExperienceNewRouteImport } from './routes/experience/new'
import { Route as ExperienceIdRouteImport } from './routes/experience/$id'
import { Route as ConfirmationsNewRouteImport } from './routes/confirmations/new'
import { Route as ConfirmationsIdRouteImport } from './routes/confirmations/$id'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelievingIndexRoute = RelievingIndexRouteImport.update({
  id: '/relieving/',
  path: '/relieving/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationsIndexRoute = ConfirmationsIndexRouteImport.update({
  id: '/confirmations/',
  path: '/confirmations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlipsNewRoute = SlipsNewRouteImport.update({
  id: '/slips/new',
  path: '/slips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SlipsIdRoute = SlipsIdRouteImport.update({
  id: '/slips/$id',
  path: '/slips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RelievingNewRoute = RelievingNewRouteImport.update({
  id: '/relieving/new',
  path: '/relieving/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RelievingIdRoute = RelievingIdRouteImport.update({
  id: '/relieving/$id',
  path: '/relieving/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersNewRoute = OffersNewRouteImport.update({
  id: '/offers/new',
  path: '/offers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIdRoute = OffersIdRouteImport.update({
  id: '/offers/$id',
  path: '/offers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceNewRoute = ExperienceNewRouteImport.update({
  id: '/experience/new',
  path: '/experience/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIdRoute = ExperienceIdRouteImport.update({
  id: '/experience/$id',
  path: '/experience/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationsNewRoute = ConfirmationsNewRouteImport.update({
  id: '/confirmations/new',
  path: '/confirmations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationsIdRoute = ConfirmationsIdRouteImport.update({
  id: '/confirmations/$id',
  path: '/confirmations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/confirmations/$id': typeof ConfirmationsIdRoute
  '/confirmations/new': typeof ConfirmationsNewRoute
  '/experience/$id': typeof ExperienceIdRoute
  '/experience/new': typeof ExperienceNewRoute
  '/offers/$id': typeof OffersIdRoute
  '/offers/new': typeof OffersNewRoute
  '/relieving/$id': typeof RelievingIdRoute
  '/relieving/new': typeof RelievingNewRoute
  '/slips/$id': typeof SlipsIdRoute
  '/slips/new': typeof SlipsNewRoute
  '/confirmations/': typeof ConfirmationsIndexRoute
  '/experience/': typeof ExperienceIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/relieving/': typeof RelievingIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/confirmations/$id': typeof ConfirmationsIdRoute
  '/confirmations/new': typeof ConfirmationsNewRoute
  '/experience/$id': typeof ExperienceIdRoute
  '/experience/new': typeof ExperienceNewRoute
  '/offers/$id': typeof OffersIdRoute
  '/offers/new': typeof OffersNewRoute
  '/relieving/$id': typeof RelievingIdRoute
  '/relieving/new': typeof RelievingNewRoute
  '/slips/$id': typeof SlipsIdRoute
  '/slips/new': typeof SlipsNewRoute
  '/confirmations': typeof ConfirmationsIndexRoute
  '/experience': typeof ExperienceIndexRoute
  '/offers': typeof OffersIndexRoute
  '/relieving': typeof RelievingIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/confirmations/$id': typeof ConfirmationsIdRoute
  '/confirmations/new': typeof ConfirmationsNewRoute
  '/experience/$id': typeof ExperienceIdRoute
  '/experience/new': typeof ExperienceNewRoute
  '/offers/$id': typeof OffersIdRoute
  '/offers/new': typeof OffersNewRoute
  '/relieving/$id': typeof RelievingIdRoute
  '/relieving/new': typeof RelievingNewRoute
  '/slips/$id': typeof SlipsIdRoute
  '/slips/new': typeof SlipsNewRoute
  '/confirmations/': typeof ConfirmationsIndexRoute
  '/experience/': typeof ExperienceIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/relieving/': typeof RelievingIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/confirmations/$id'
    | '/confirmations/new'
    | '/experience/$id'
    | '/experience/new'
    | '/offers/$id'
    | '/offers/new'
    | '/relieving/$id'
    | '/relieving/new'
    | '/slips/$id'
    | '/slips/new'
    | '/confirmations/'
    | '/experience/'
    | '/offers/'
    | '/relieving/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/confirmations/$id'
    | '/confirmations/new'
    | '/experience/$id'
    | '/experience/new'
    | '/offers/$id'
    | '/offers/new'
    | '/relieving/$id'
    | '/relieving/new'
    | '/slips/$id'
    | '/slips/new'
    | '/confirmations'
    | '/experience'
    | '/offers'
    | '/relieving'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/confirmations/$id'
    | '/confirmations/new'
    | '/experience/$id'
    | '/experience/new'
    | '/offers/$id'
    | '/offers/new'
    | '/relieving/$id'
    | '/relieving/new'
    | '/slips/$id'
    | '/slips/new'
    | '/confirmations/'
    | '/experience/'
    | '/offers/'
    | '/relieving/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ConfirmationsIdRoute: typeof ConfirmationsIdRoute
  ConfirmationsNewRoute: typeof ConfirmationsNewRoute
  ExperienceIdRoute: typeof ExperienceIdRoute
  ExperienceNewRoute: typeof ExperienceNewRoute
  OffersIdRoute: typeof OffersIdRoute
  OffersNewRoute: typeof OffersNewRoute
  RelievingIdRoute: typeof RelievingIdRoute
  RelievingNewRoute: typeof RelievingNewRoute
  SlipsIdRoute: typeof SlipsIdRoute
  SlipsNewRoute: typeof SlipsNewRoute
  ConfirmationsIndexRoute: typeof ConfirmationsIndexRoute
  ExperienceIndexRoute: typeof ExperienceIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  RelievingIndexRoute: typeof RelievingIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relieving/': {
      id: '/relieving/'
      path: '/relieving'
      fullPath: '/relieving/'
      preLoaderRoute: typeof RelievingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmations/': {
      id: '/confirmations/'
      path: '/confirmations'
      fullPath: '/confirmations/'
      preLoaderRoute: typeof ConfirmationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slips/new': {
      id: '/slips/new'
      path: '/slips/new'
      fullPath: '/slips/new'
      preLoaderRoute: typeof SlipsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slips/$id': {
      id: '/slips/$id'
      path: '/slips/$id'
      fullPath: '/slips/$id'
      preLoaderRoute: typeof SlipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relieving/new': {
      id: '/relieving/new'
      path: '/relieving/new'
      fullPath: '/relieving/new'
      preLoaderRoute: typeof RelievingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relieving/$id': {
      id: '/relieving/$id'
      path: '/relieving/$id'
      fullPath: '/relieving/$id'
      preLoaderRoute: typeof RelievingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/new': {
      id: '/offers/new'
      path: '/offers/new'
      fullPath: '/offers/new'
      preLoaderRoute: typeof OffersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$id': {
      id: '/offers/$id'
      path: '/offers/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof OffersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/new': {
      id: '/experience/new'
      path: '/experience/new'
      fullPath: '/experience/new'
      preLoaderRoute: typeof ExperienceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$id': {
      id: '/experience/$id'
      path: '/experience/$id'
      fullPath: '/experience/$id'
      preLoaderRoute: typeof ExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmations/new': {
      id: '/confirmations/new'
      path: '/confirmations/new'
      fullPath: '/confirmations/new'
      preLoaderRoute: typeof ConfirmationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmations/$id': {
      id: '/confirmations/$id'
      path: '/confirmations/$id'
      fullPath: '/confirmations/$id'
      preLoaderRoute: typeof ConfirmationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ConfirmationsIdRoute: ConfirmationsIdRoute,
  ConfirmationsNewRoute: ConfirmationsNewRoute,
  ExperienceIdRoute: ExperienceIdRoute,
  ExperienceNewRoute: ExperienceNewRoute,
  OffersIdRoute: OffersIdRoute,
  OffersNewRoute: OffersNewRoute,
  RelievingIdRoute: RelievingIdRoute,
  RelievingNewRoute: RelievingNewRoute,
  SlipsIdRoute: SlipsIdRoute,
  SlipsNewRoute: SlipsNewRoute,
  ConfirmationsIndexRoute: ConfirmationsIndexRoute,
  ExperienceIndexRoute: ExperienceIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  RelievingIndexRoute: RelievingIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
