/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlipsNewRouteImport } from './routes/slips/new'
import { Route as SlipsIdRouteImport } from './routes/slips/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlipsNewRoute = SlipsNewRouteImport.update({
  id: '/slips/new',
  path: '/slips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SlipsIdRoute = SlipsIdRouteImport.update({
  id: '/slips/$id',
  path: '/slips/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slips/$id': typeof SlipsIdRoute
  '/slips/new': typeof SlipsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/slips/$id': typeof SlipsIdRoute
  '/slips/new': typeof SlipsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slips/$id': typeof SlipsIdRoute
  '/slips/new': typeof SlipsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/slips/$id' | '/slips/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/slips/$id' | '/slips/new'
  id: '__root__' | '/' | '/slips/$id' | '/slips/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlipsIdRoute: typeof SlipsIdRoute
  SlipsNewRoute: typeof SlipsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slips/new': {
      id: '/slips/new'
      path: '/slips/new'
      fullPath: '/slips/new'
      preLoaderRoute: typeof SlipsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slips/$id': {
      id: '/slips/$id'
      path: '/slips/$id'
      fullPath: '/slips/$id'
      preLoaderRoute: typeof SlipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlipsIdRoute: SlipsIdRoute,
  SlipsNewRoute: SlipsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
